---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install: 
  - gem install bundler -v 2.0.1
  - bundle install
  
before_script:
  - rubocop
  - RAILS_ENV=test bundle exec rspec

script:
  - gem build nmax.gemspec
